//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSHfiletype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSHfiletype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string AlphagbText {
            get {
                return ResourceManager.GetString("AlphagbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha from image transparency.
        /// </summary>
        internal static string AlphatransText {
            get {
                return ResourceManager.GetString("AlphatransText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name.
        /// </summary>
        internal static string dirnamelblText {
            get {
                return ResourceManager.GetString("dirnamelblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fsh Type.
        /// </summary>
        internal static string FshtypeText {
            get {
                return ResourceManager.GetString("FshtypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new map.
        /// </summary>
        internal static string GenmapText {
            get {
                return ResourceManager.GetString("GenmapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Mipmaps.
        /// </summary>
        internal static string GenmipText {
            get {
                return ResourceManager.GetString("GenmipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use original Alpha.
        /// </summary>
        internal static string OrigAlphaText {
            get {
                return ResourceManager.GetString("OrigAlphaText", resourceCulture);
            }
        }
    }
}
